config/routes.rb
Rails.application.routes.draw do
  get 'orders/create'
  resources :tasks, only: :index do
    resources :orders, only: :create
  end
  resources :orders do
    collection do
      get 'completed'
    end
  end
  root to: 'tasks#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :users, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  has_many :tasks, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def create
    @task = Task.find(params[:task_id])
    @order = Order.new(task: @task, user: current_user)
      if @order.save
        redirect_to tasks_path, notice: 'La tarea ha sido ingresada'
      else
        redirect_to tasks_path, alert: @order.errors.full_messages
      end
  end
  def completed
    @orders = current_user.orders
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= completed_orders_path %>">Tareas Terminadas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if current_user %>
        <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete%>
      <% else %>
        <%= link_to 'Iniciar Sesion', new_user_session_path%>
      <% end %>

    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/completed.html.erb
<div class="container">
  <div class="row">
    <% @orders.each_slice(4) do |row| %>
      <% row.each do |i| %>
        <div class="col-md-3">
          <div class="card">
            <%= image_tag i.task.photo, class: 'card-img-top' %>
            <div class="body">
              <h5><%= i.task.name %></h5>
            </div>
          </div>
        </div>
      <% end %>
      <div class="w-100"></div>
    <% end %>
  </div>
</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <% @tasks.each_slice(4) do |row| %>
      <% row.each do |task| %>
        <div class="col">
          <div class="card">
            <%= image_tag task.photo, class: 'card-img-top'%>
            <div class="body">

              <h5><%= task.name%></h5>
              <% if current_user.tasks.where(orders:{ready: true})%>
                  <%= link_to "Listo", task_orders_path(task), class: 'btn btn-success', method: :post %>
              <% else %>
                  <%= link_to "No Listo", task_orders_path(task), class: 'btn btn-danger', method: :post %>
              <% end %>
            </div>
          </div>
        </div>
      <% end%>
      <div class="w-100"></div>
      <% end %>
  </div>
</div>